apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-hello-template
  title: Python Hello Template
  description: Onboard snowflake workspace.
  tags:
    - snowflake
    - ucp
spec:
  owner: backstage/engineering
  type: service

  parameters:
    - title: Provide your name
      required:
        - first_name
        - last_name
      properties:
        first_name:
          title: First Name
          type: string
          description: Your first name.
        last_name:
          title: Last Name
          type: string
          description: Your last name.

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./template
        values:
          first_name: ${{ parameters.first_name }}
          last_name: ${{ parameters.last_name }}

    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: "A Python project that says hello to ${{ parameters.first_name }} ${{ parameters.last_name }}."
        repoUrl: ${{ parameters.repoUrl }}

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in GitHub
        icon: github
        url: ${{ steps.publish.output.remoteUrl }}