apiVersion: v1
kind: Service
metadata:
  name: edw-nginx-edwuser-service
  namespace: edw-nginx
spec:
  selector:
    app: edw-nginx-edwuser
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP